version: '3.8'
services:
    ui:
        container_name: tomr-ui
        build:
            context: ./ui/
        image: tomr-ui
        depends_on:
            - cache
            - server
        ports:
            - 80:80
        links:
            - server
    server:
        container_name: tomr-server
        build:
            context: ./server/
        image: tomr-server
        depends_on:
            - cache
        environment:
            NODE_ENV: production
            REDIS_HOST: cache
            REDIS_PORT: 6379
        links:
            - cache
    cache:
        image: redis:6.2-alpine
        restart: always
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data
volumes:
    cache:
        driver: local
